<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>2.0.2</Version>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>NocturneModernController.InputHelper</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Optimize>true</Optimize>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
</Project>
